name: ci_workflows

on: pull_request
jobs:
    test: 
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repositório
              uses: actions/checkout@v4

            - name: Instalando Python
              uses: actions/setup-python@v5
              with: 
                python-version: '3.11.5'

            - name: Instalando Dependências
              run: pip install -r requirements.txt

            - name: Rodando os Testes da Aplicações
              run: pytest tests/test_contrato.py

